---
services:
  web: 
    container_name: wordpress
    # dockerfile: ./Dockerfile
    build: .
    ports: 
      - 8080:8080
      - 2222:2222
    env_file: 
      - .env
    environment:
      - WORDPRESS_DB_NAME=${WORDPRESS_DATABASE_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DATABASE_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DATABASE_PASSWORD}
      - WORDPRESS_DEBUG=true
      - WP_DEBUG_LOG=true
      - WP_DEBUG_DISPLAY=true
      - WP_ALLOW_REPAIR=true
