# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build & Deploy Container App

concurrency: 
  group: Container App
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - uses: thefringeninja/action-minver@2.0.0-preview1
      id: minver
      with:
        # Optional. Specifies which part of the version to auto-increment.
        auto-increment: patch
        # Optional. Sets custom build metadata for your semantic version.
        # build-metadata: ${{ github.sha }}
        # Optional. Specifies the default pre-release phase.
        default-pre-release-phase: preview
        # Optional. Specifies the minimum version to use when no tags exist.
        minimum-major-minor: 0.0
        # Optional. Specifies the prefix of the tags
        tag-prefix: v
        # Optional. Specifies the log level.
        verbosity: info

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/mocsocialclub/wordpress
        flavor: |
          latest=auto
        labels: |
          org.opencontainers.image.version=${{ steps.minver.outputs.version }}
          org.opencontainers.image.licenses=MIT
          org.opencontainers.image.description="The Website for the MOC Social Club of Philadelphia"
        tags: |
          type=raw,value=latest
          type=ref,event=branch
          type=ref,event=pr
          type=ref,event=tag
          type=raw,value=${{ steps.minver.outputs.version }}
          type=sha,format=long,pattern={{sha}},prefix=
          type=sha,format=short,prefix=
          type=schedule
          type=schedule,pattern=nightly
          type=schedule,pattern={{date 'YYYYMMDD'}}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_d30acff22a464be299bd4fe51ef224dc }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0e16211552d240b0a098ca9fb906234c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v6.7.0
      with:
        context: .
        pull: true
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        file: ./Dockerfile
        platforms: linux/amd64 #,linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max
        annotations: ${{ steps.meta.outputs.annotations }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mocsocialclub'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_11eedf9995b24e94bf0f3a5ba68e76d1 }}
        images: ghcr.io/mocsocialclub/wordpress:${{ github.sha }}
