# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build & Deploy Container App

concurrency: 
  group: Container App
  cancel-in-progress: true

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_d30acff22a464be299bd4fe51ef224dc }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0e16211552d240b0a098ca9fb906234c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/mocsocialclub/wordpress:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mocsocialclub'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_11eedf9995b24e94bf0f3a5ba68e76d1 }}
        images: ghcr.io/mocsocialclub/wordpress:${{ github.sha }}
